from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.task_rule import TaskRule
from openapi_server import util

from openapi_server.models.task_rule import TaskRule  # noqa: E501

class UpdateTaskRuleRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, new_data=None):  # noqa: E501
        """UpdateTaskRuleRequest - a model defined in OpenAPI

        :param new_data: The new_data of this UpdateTaskRuleRequest.  # noqa: E501
        :type new_data: TaskRule
        """
        self.openapi_types = {
            'new_data': TaskRule
        }

        self.attribute_map = {
            'new_data': 'newData'
        }

        self._new_data = new_data

    @classmethod
    def from_dict(cls, dikt) -> 'UpdateTaskRuleRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The updateTaskRule_request of this UpdateTaskRuleRequest.  # noqa: E501
        :rtype: UpdateTaskRuleRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def new_data(self) -> TaskRule:
        """Gets the new_data of this UpdateTaskRuleRequest.


        :return: The new_data of this UpdateTaskRuleRequest.
        :rtype: TaskRule
        """
        return self._new_data

    @new_data.setter
    def new_data(self, new_data: TaskRule):
        """Sets the new_data of this UpdateTaskRuleRequest.


        :param new_data: The new_data of this UpdateTaskRuleRequest.
        :type new_data: TaskRule
        """

        self._new_data = new_data
